# Generated by Django 3.0.5 on 2021-01-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='email',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='username',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
