# Generated by Django 3.1.5 on 2021-01-21 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_userdata_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message='emailid must be entered in the correct format', regex='^[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+$')]),
        ),
    ]
