# Generated by Django 3.0.8 on 2021-01-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20210121_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='pro_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
