# Generated by Django 3.0.8 on 2021-01-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20210126_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='pro_image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
